---
title: "qrf_covariate_selection"
author: "Mark Roes"
date: "4/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lemon)
library(tidyverse)
```

```{r load data}
data("MINE_stats")
load("data/MINE_stats.rda")
#mic_dat = rbind(mine_plot_list$Redds, mine_plot_list$Summer_CHaMP, mine_plot_list$Summer_DASH, mine_plot_list$Winter) %>%
#select(species, MetricCategory, Metric, dataset, MIC, Name)
  
```

```{r MIC chnkfig}
mine_chnk_p = mine_plot_list %>%
  map(.f = function(x) {
    x %>%
      filter(species == "Chinook") %>%
      # filter(MetricCategory != 'Other') %>%
      # put the metric names in descending order by MIC
      mutate_at(vars(Metric, Name),
                list(~ fct_reorder(., .x = MIC))) %>%
      arrange(desc(Metric)) %>%
      ggplot(aes(x = Name,
                 y = MIC)) +
      facet_wrap(~MetricCategory, scales = 'free_y') +
      geom_col() +
      coord_flip() +
      # scale_fill_viridis_d() +
      scale_fill_brewer(palette = 'Set3',
                        guide = guide_legend(nrow = 2)) +
      theme(legend.position = 'bottom',
            axis.text = element_text(size = 6)) +
      labs(title = unique(x$dataset),
           fill = 'Category')
  })


pdf(paste0('MINE_Chnk2.pdf'),
    width = 16,
    height = 9)
for(i in 1:length(mine_chnk_p)) {
  print(mine_chnk_p[[i]])
}
dev.off()
```


```{r MIC stlhd fig}
mine_stlhd_p = mine_plot_list %>%
  map(.f = function(x) {
    x %>%
      filter(species == "Steelhead") %>%
      # filter(MetricCategory != 'Other') %>%
      # put the metric names in descending order by MIC
      mutate_at(vars(Metric, Name),
                list(~ fct_reorder(., .x = MIC))) %>%
      arrange(desc(Metric)) %>%
      ggplot(aes(x = Name,
                 y = MIC)) +
      facet_wrap(~MetricCategory, scales = 'free_y') +
      geom_col() +
      coord_flip() +
      # scale_fill_viridis_d() +
      scale_fill_brewer(palette = 'Set3',
                        guide = guide_legend(nrow = 2)) +
      theme(legend.position = 'bottom',
            axis.text = element_text(size = 6)) +
      labs(title = unique(x$dataset),
           fill = 'Category')
  })


pdf(paste0('MINE_stlhd2.pdf'),
    width = 16,
    height = 9)
for(i in 1:length(mine_stlhd_p)) {
  print(mine_stlhd_p[[i]])
}
dev.off()

```


Test MIC difference 

```{r MIC SpeciesDiff}
stlhd = mine_plot_list %>%
  map(.f = function(x) {
    x %>%
      filter(species == "Steelhead")
    }) %>%
  bind_rows()
  

chnk = mine_plot_list %>%
  map(.f = function(x) {
    x %>%
      filter(species == "Chinook") 
    }) %>%
  bind_rows()
  


mic_diff = left_join(stlhd,chnk[,c(1:4,12)], by = c("MetricCategory","Metric","dataset")) %>%
  mutate(MIC_diff = abs(MIC.x - MIC.y)) %>%
  mutate(MIC_rel_diff = MIC.y/MIC.x) %>%
  split(.$dataset)


mic_diff_p = mic_diff %>%
  map(.f = function(x) {
    x %>%
      mutate_at(vars(Metric, Name),
                list(~ fct_reorder(., .x = MIC.x))) %>%
      arrange(desc(Metric)) %>%
      ggplot() +
      geom_col(aes(x = Name,
                 y = MIC_diff)) +
      geom_col(aes(x= Name,
                 y = MIC.x), alpha = 0.5)+
      facet_wrap(~MetricCategory, scales = 'free_y') +
      coord_flip() +
      # scale_fill_viridis_d() +
      scale_fill_brewer(palette = 'Set3',
                        guide = guide_legend(nrow = 2)) +
      theme(legend.position = 'bottom',
            axis.text = element_text(size = 6)) +
      labs(title = unique(x$dataset),
           fill = 'Category',
           x = element_blank(),
           y = "Steelhead MIC and |MIC Difference with Chinook|)")
  })


pdf(paste0('MIC_diff.pdf'),
    width = 16,
    height = 9)

for(i in 1:length(mic_diff_p)) {
  print(mic_diff_p[[i]])
}

dev.off()

```